//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

pub use super::category::Entity as Category;
pub use super::post::Entity as Post;
pub use super::post_tag::Entity as PostTag;
pub use super::tag::Entity as Tag;

pub use super::category::Model as CategoryModel;
pub use super::post::Model as PostModel;
pub use super::post_tag::Model as PostTagModel;
pub use super::tag::Model as TagModel;
