//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::category::Entity as Category;
pub use super::friend::Entity as Friend;
pub use super::post::Entity as Post;

pub use super::category::Model as CategoryModel;
pub use super::friend::Model as FriendModel;
pub use super::post::Model as PostModel;
